import type { SemanticBadgeTone } from "./semantic-badge";
import SemanticBadge from "./semantic-badge";
import type { AiAssistanceDisclosure as AiAssistanceDisclosureModel } from "../ai-assistance-model";
import { cx } from "../utils/cx";

import styles from "./ai-assistance-disclosure.module.css";

type AiAssistanceDisclosureProps = {
  disclosure: AiAssistanceDisclosureModel;
  className?: string;
};

export default function AiAssistanceDisclosure({
  disclosure,
  className,
}: AiAssistanceDisclosureProps) {
  const status = getDisclosureStatus(disclosure);
  const facts = [
    ["Preparation", PREPARATION_LABELS[disclosure.preparation]],
    ["Availability", AVAILABILITY_LABELS[disclosure.availability]],
    ["Evidence", EVIDENCE_LABELS[disclosure.evidence.state]],
    ["Human review", REVIEW_LABELS[disclosure.humanReview.state]],
    ["Client use", CLIENT_USE_LABELS[disclosure.clientUse]],
    ["Freshness", FRESHNESS_LABELS[disclosure.freshness.state]],
  ] as const;

  return (
    <details className={cx(styles.disclosure, className)}>
      <summary className={styles.summary}>
        <SemanticBadge tone={status.tone}>{status.label}</SemanticBadge>
        <span className={styles.summaryLabel}>How this was prepared</span>
        <span className={styles.scope}>{disclosure.scopeLabel}</span>
      </summary>
      <div className={styles.body}>
        <dl className={styles.factGrid}>
          {facts.map(([label, value]) => (
            <div className={styles.fact} key={label}>
              <dt>{label}</dt>
              <dd>{value}</dd>
            </div>
          ))}
        </dl>

        {disclosure.limitations.length > 0 ? (
          <div className={styles.limitations}>
            <strong>What to consider</strong>
            <ul>
              {disclosure.limitations.map((limitation) => (
                <li key={limitation}>{limitation}</li>
              ))}
            </ul>
          </div>
        ) : null}

        {disclosure.diagnostics.length > 0 ? (
          <dl className={styles.diagnostics} aria-label="Technical support details">
            {disclosure.diagnostics.map((item) => (
              <div key={`${item.label}-${item.value}`}>
                <dt>{item.label}</dt>
                <dd>{item.value}</dd>
              </div>
            ))}
          </dl>
        ) : null}
      </div>
    </details>
  );
}

function getDisclosureStatus(disclosure: AiAssistanceDisclosureModel): {
  label: string;
  tone: SemanticBadgeTone;
} {
  if (disclosure.availability === "unavailable") {
    return { label: "Output unavailable", tone: "warn" };
  }
  if (disclosure.availability === "stale") {
    return { label: "Stale output", tone: "warn" };
  }
  if (disclosure.availability === "partial") {
    return { label: "Partial output", tone: "warn" };
  }
  if (disclosure.availability === "simulation") {
    return { label: "Simulation output", tone: "warn" };
  }
  if (disclosure.preparation === "unavailable") {
    return { label: "Provenance unavailable", tone: "warn" };
  }
  if (disclosure.humanReview.state === "review-required") {
    return { label: "Live output • review required", tone: "warn" };
  }
  if (disclosure.humanReview.state === "rejected") {
    return { label: "Live output • review rejected", tone: "danger" };
  }
  if (disclosure.preparation === "deterministic") {
    return { label: "Live rule-based output", tone: "default" };
  }
  if (disclosure.preparation === "source-authored") {
    return { label: "Live source-authored output", tone: "default" };
  }
  if (disclosure.preparation === "requested") {
    return { label: "Generation requested", tone: "warn" };
  }
  return { label: "Live AI-assisted output", tone: "default" };
}

const PREPARATION_LABELS: Record<AiAssistanceDisclosureModel["preparation"], string> = {
  "source-authored": "Published by the source system",
  deterministic: "Prepared from defined rules",
  "ai-assisted": "Prepared with AI assistance",
  "ai-generated": "Generated by an AI workflow",
  requested: "Generation requested; no output returned",
  unavailable: "Generation provenance unavailable",
};

const AVAILABILITY_LABELS: Record<AiAssistanceDisclosureModel["availability"], string> = {
  live: "Current output is available",
  partial: "Output is incomplete",
  simulation: "Simulation output only",
  stale: "Historical output; a newer run may be available",
  unavailable: "No usable output is available",
};

const EVIDENCE_LABELS: Record<AiAssistanceDisclosureModel["evidence"]["state"], string> = {
  supported: "Source evidence attached",
  limited: "Limited source evidence",
  missing: "Source evidence not published",
  conflicted: "Source evidence requires reconciliation",
};

const REVIEW_LABELS: Record<AiAssistanceDisclosureModel["humanReview"]["state"], string> = {
  "not-required": "Human review not required",
  "review-required": "Human review required",
  reviewed: "Human review recorded",
  rejected: "Human review rejected",
  unavailable: "Human-review status not available",
};

const CLIENT_USE_LABELS: Record<AiAssistanceDisclosureModel["clientUse"], string> = {
  "internal-only": "Internal working use only",
  "eligible-after-review": "Eligible after required review",
  approved: "Approved for client use",
  blocked: "Not approved for client use",
  unavailable: "Client-use status not available",
};

const FRESHNESS_LABELS: Record<AiAssistanceDisclosureModel["freshness"]["state"], string> = {
  current: "Current as reported by the source",
  stale: "Source reports stale evidence",
  "not-reported": "Freshness not reported",
};
