export const lotusThemeTokens = {
  color: {
    surface: {
      canvas: "#f3f5f7",
      canvasAlt: "#edf1f4",
      panel: "#ffffff",
      panelAlt: "#f7f9fb",
    },
    text: {
      primary: "#17202b",
      muted: "#697586",
    },
    border: {
      default: "#d9e0e7",
      subtle: "1px solid #d9e0e7",
    },
    brand: {
      base: "#365f8b",
      strong: "#17202b",
      soft: "#eef3f8",
      accent: "#a9b7c7",
      highlight: "#57799d",
    },
    semantic: {
      success: "#2f6b48",
      warning: "#8a5b11",
      danger: "#b54738",
      analyticPositive: "#4f6f8f",
      analyticPositiveSoft: "#6f89a3",
      analyticNegative: "#8a6757",
      analyticNegativeSoft: "#ab8675",
    },
    statusBackground: {
      success: "#eef6f1",
      warning: "#fff6e8",
      danger: "#fdf0ee",
      neutral: "#f3f4f6",
    },
  },
  typography: {
    fontFamily: {
      ui: '"Public Sans", "Segoe UI", sans-serif',
      display: '"Cormorant Garamond", Georgia, serif',
      mono: '"IBM Plex Mono", ui-monospace, monospace',
    },
    size: {
      text2xs: "0.6875rem",
      textXs: "0.75rem",
      textSm: "0.875rem",
      textMd: "0.875rem",
      textLg: "1.0625rem",
      textXl: "1rem",
      text2xl: "1.125rem",
      text3xl: "2rem",
    },
    lineHeight: {
      tight: 1.15,
      snug: 1.3,
      body: 1.6,
    },
    tracking: {
      label: "0.08em",
      tight: "-0.04em",
      shellBrand: "-0.035em",
      shellUi: "-0.015em",
      analyticLabel: "0.06em",
    },
    variant: {
      pageTitle: {
        size: "clamp(1.45rem, 1.6vw, 1.9rem)",
        weight: 700,
        lineHeight: 1.05,
        tracking: "-0.04em",
      },
      sectionTitle: {
        size: "1.125rem",
        weight: 650,
        lineHeight: 1.2,
        tracking: "-0.02em",
      },
      cardTitle: {
        size: "1rem",
        weight: 650,
        lineHeight: 1.24,
        tracking: "-0.015em",
      },
      body: {
        size: "0.875rem",
        lineHeight: 1.6,
      },
      secondary: {
        size: "0.75rem",
        lineHeight: 1.4,
      },
      label: {
        size: "0.6875rem",
        weight: 800,
        lineHeight: 1.3,
        tracking: "0.08em",
      },
      metricValue: {
        size: "1.75rem",
        weight: 700,
        lineHeight: 1.12,
        tracking: "-0.03em",
      },
      metricValueCompact: {
        size: "1rem",
        weight: 750,
        lineHeight: 1.2,
      },
    },
    workbench: {
      textCompact: "0.75rem",
      textCompactStrong: "0.8125rem",
      summaryTitle: "1rem",
      summaryVisualLabel: "0.8125rem",
      summaryVisualValue: "0.875rem",
      summaryVisualMeta: "0.75rem",
      analyticLabel: "0.6875rem",
      analyticChip: "0.6875rem",
      analyticSupport: "0.71875rem",
      analyticContextValue: "0.78125rem",
      analyticSubtitle: "0.78125rem",
      analyticHeading: "0.875rem",
      analyticFallback: "0.75rem",
    },
  },
  spacing: {
    step1: "4px",
    step2: "8px",
    step3: "12px",
    step4: "16px",
    step5: "20px",
    step6: "24px",
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    control: 12,
    panel: 16,
  },
  elevation: {
    subtle: "0 1px 2px rgba(17, 24, 39, 0.03)",
  },
  focus: {
    ring: "0 0 0 2px rgba(54, 95, 139, 0.32)",
  },
  layout: {
    workbenchSectionGap: "16px",
    workbenchCardPadding: "24px",
    workbenchCardPaddingCompact: "20px",
    workbenchPageFrameGap: "16px",
    workbenchPageFrameHeaderPadding: "4px",
    workbenchSummaryBodyGap: "12px",
    workbenchTitleGap: "4px",
    workbenchMetricStripGap: "8px",
    workbenchRailWidth: "340px",
    workbenchRailCardPadding: "20px",
    workstationShellGap: "20px",
    workstationRailWidth: "280px",
    workstationSideWidth: "320px",
  },
  control: {
    height: {
      touchTarget: "44px",
      compactToolbar: "36px",
    },
  },
  table: {
    rowHeight: {
      compact: "44px",
      comfortable: "52px",
    },
    cellPadding: {
      x: "16px",
      y: "12px",
    },
  },
  zIndex: {
    shellHeader: 20,
  },
} as const;
