"use client";

import { AnalyticsTable, MetricRow, Text } from "@/design-system";
import PmOperatingQualityStateBadge from "@/features/workbench/components/pm-operating-quality-state-badge";
import { formatPmQualityReasonCodeList } from "@/features/workbench/pm-operating-quality-panel-helpers";
import type { PmOperatingQualityPanelModel } from "@/features/workbench/pm-operating-quality-view-model";

type Props = {
  model: PmOperatingQualityPanelModel;
};

export default function PmOperatingQualityFairnessEvidenceCard({ model }: Props) {
  const hasFairnessDetail = model.fairnessAnalysisId !== "N/A";

  return (
    <div className="pm-quality-evidence-grid">
      <div className="pm-quality-fairness-detail">
        <div className="pm-quality-card-header">
          <Text as="h3" variant="subsectionTitle">
            Fairness Analysis Detail
          </Text>
          <PmOperatingQualityStateBadge
            state={hasFairnessDetail ? model.fairnessState : "PENDING"}
            label={hasFairnessDetail ? undefined : "No detail"}
          />
        </div>
        <div
          className="pm-quality-fairness-preview-posture"
          aria-label="PM operating quality fairness analysis posture"
        >
          <MetricRow
            label="Gateway Read State"
            value={
              hasFairnessDetail
                ? "Fairness analysis returned by Gateway"
                : "Awaiting persisted analysis detail or preview"
            }
          />
          <MetricRow label="Preview Readiness" value={model.fairnessPreviewReadiness} />
          <MetricRow
            label="Authority Boundary"
            value="Manage owns segment posture and fairness spread; Workbench does not calculate or rank"
          />
        </div>
        <div className="pm-quality-detail-grid">
          <MetricRow label="Product" value={model.fairnessDetail.product} />
          <MetricRow label="As Of" value={model.fairnessDetail.asOfDate} />
          <MetricRow
            label="Minimum Segment Runs"
            value={model.fairnessDetail.minimumSegmentScoreRunCount}
          />
          <MetricRow
            label="Maximum Governed Spread"
            value={model.fairnessDetail.maximumAverageScoreSpread}
          />
          <MetricRow
            label="Observed Spread"
            value={model.fairnessDetail.observedAverageScoreSpread}
          />
          <MetricRow label="Generated By" value={model.fairnessDetail.generatedBy} />
        </div>
        <div className="pm-quality-detail-stack">
          <MetricRow label="Generated At" value={model.fairnessDetail.generatedAt} />
          <MetricRow label="Analysis Source Refs" value={model.fairnessDetail.sourceRefs} />
          <MetricRow
            label="Analysis Reason Codes"
            value={formatPmQualityReasonCodeList(model.fairnessDetail.reasonCodes)}
          />
          <MetricRow label="Forbidden Use Boundary" value={model.fairnessDetail.forbiddenUses} />
        </div>
      </div>

      <AnalyticsTable
        ariaLabel="PM operating quality persisted fairness analyses"
        variant="analysis"
        density="compact"
        columns={[
          { key: "analysis", label: "Fairness Analysis" },
          { key: "policy", label: "Policy" },
          { key: "state", label: "State" },
          { key: "asOf", label: "As Of" },
          { key: "spread", label: "Observed Spread" },
          { key: "segments", label: "Segments" },
          { key: "generatedBy", label: "Generated By" },
          { key: "source", label: "Source Refs" },
          { key: "reason", label: "Reason" },
        ]}
        rows={model.fairnessAnalysisRows.map((row) => ({
          key: row.key,
          cells: [
            <strong key={`${row.key}-analysis`}>{row.fairnessAnalysisId}</strong>,
            row.policy,
            <PmOperatingQualityStateBadge key={`${row.key}-state`} state={row.state} />,
            row.asOfDate,
            row.observedSpread,
            row.segmentCount,
            row.generatedBy,
            row.sourceRefs,
            formatPmQualityReasonCodeList(row.reasonCodes),
          ],
        }))}
        emptyState={{
          title: "No persisted fairness analyses returned",
          body: "Workbench waits for Manage-persisted fairness analysis evidence through Gateway.",
        }}
      />

      <AnalyticsTable
        ariaLabel="PM operating quality source segments"
        variant="analysis"
        density="compact"
        columns={[
          { key: "segment", label: "Source Segment" },
          { key: "type", label: "Type" },
          { key: "count", label: "Score Runs" },
          { key: "source", label: "Source Refs" },
        ]}
        rows={model.sourceSegmentRows.map((row) => ({
          key: row.key,
          cells: [
            <strong key={`${row.key}-segment`}>{row.segment}</strong>,
            row.segmentType,
            row.scoreRunCount,
            row.sourceRefs,
          ],
        }))}
        emptyState={{
          title: "No source-defined segments returned",
          body: "Workbench waits for Manage/Gateway segment assignments before enabling fairness review.",
        }}
      />

      <AnalyticsTable
        ariaLabel="PM operating quality fairness segments"
        variant="analysis"
        density="compact"
        columns={[
          { key: "segment", label: "Segment" },
          { key: "type", label: "Type" },
          { key: "state", label: "State" },
          { key: "count", label: "Score Runs" },
          { key: "average", label: "Average Score" },
          { key: "range", label: "Score Range" },
          { key: "scoreRunRefs", label: "Score Run Refs" },
          { key: "source", label: "Source Refs" },
          { key: "reason", label: "Reason" },
        ]}
        rows={model.fairnessSegmentRows.map((row) => ({
          key: row.key,
          cells: [
            <strong key={`${row.key}-segment`}>{row.segment}</strong>,
            row.segmentType,
            <PmOperatingQualityStateBadge key={`${row.key}-state`} state={row.state} />,
            row.scoreRunCount,
            row.averageScore,
            `${row.minimumScore} / ${row.maximumScore}`,
            row.scoreRunRefs,
            row.sourceRefs,
            formatPmQualityReasonCodeList(row.reasonCodes),
          ],
        }))}
        emptyState={{
          title: "No fairness segment preview returned",
          body:
            model.fairnessSegmentRequests.length >= 2
              ? "Run a Manage fairness preview to inspect source-defined segment posture."
              : "Manage has not returned source-defined segment assignments for a fairness preview.",
        }}
      />
    </div>
  );
}
