export const DPM_AI_WORKFLOW_PROFILES = {
  "proof-pack-memo": {
    scopeLabel: "Portfolio decision memo",
    packId: "dpm_pm_memo.pack",
    workflowSurface: "dpm-proof-pack-ai-evidence",
    sourceSupportabilityAuthority: "lotus-manage:RFC-0040",
    liveSourceSupportabilityStates: ["READY", "SUPPORTED"],
    sourceInputField: "ai_evidence_input",
    sourceIdentityField: "proof_pack_id",
    requestedOutputs: [
      "pm_memo",
      "rationale_summary",
      "approval_checklist",
      "risk_caveats",
      "operations_handoff",
      "evidence_gaps",
    ],
    materialTitle: "Decision memo material",
    materialFields: [
      { key: "pm_memo", label: "Portfolio manager memo" },
      { key: "memo", label: "Portfolio manager memo" },
      { key: "memo_sections", label: "Memo sections" },
      { key: "rationale_summary", label: "Investment rationale" },
      { key: "approval_checklist", label: "Approval checklist" },
      { key: "risk_caveats", label: "Risk considerations" },
      { key: "operations_handoff", label: "Operations handoff" },
      { key: "evidence_gaps", label: "Evidence gaps" },
      { key: "evidence_gap_count", label: "Evidence gaps" },
      { key: "escalation_required", label: "Escalation required" },
      { key: "dpm_pm_memo_status", label: "Review posture" },
      { key: "state", label: "Review posture" },
      { key: "scope", label: "Permitted scope" },
    ],
  },
  "wave-memo": {
    scopeLabel: "Rebalance wave review memo",
    packId: "dpm_wave_pm_memo.pack",
    workflowSurface: "dpm-wave-ai-evidence",
    sourceSupportabilityAuthority: "lotus-manage:RFC-0041",
    liveSourceSupportabilityStates: ["READY"],
    sourceInputField: "wave_report_input",
    sourceIdentityField: "wave_id",
    requestedOutputs: [
      "wave_pm_memo",
      "wave_rationale_summary",
      "approval_checklist",
      "risk_caveats",
      "operations_handoff",
      "evidence_gaps",
    ],
    materialTitle: "Rebalance review material",
    materialFields: [
      { key: "wave_pm_memo", label: "Rebalance memo" },
      { key: "memo_sections", label: "Memo sections" },
      { key: "wave_rationale_summary", label: "Rebalance rationale" },
      { key: "approval_checklist", label: "Approval checklist" },
      { key: "risk_caveats", label: "Risk considerations" },
      { key: "operations_handoff", label: "Operations handoff" },
      { key: "evidence_gaps", label: "Evidence gaps" },
      { key: "review_required", label: "Review required" },
      { key: "state", label: "Review posture" },
      { key: "scope", label: "Permitted scope" },
    ],
  },
  "operations-handoff": {
    scopeLabel: "Operations handoff summary",
    packId: "dpm_operations_handoff_summary.pack",
    workflowSurface: "dpm-operations-handoff-ai-evidence",
    sourceSupportabilityAuthority: "lotus-manage:RFC-0041",
    liveSourceSupportabilityStates: ["READY"],
    sourceInputField: "wave_report_input",
    sourceIdentityField: "wave_id",
    requestedOutputs: [
      "operations_summary",
      "execution_prerequisites",
      "blocking_conditions",
      "support_references",
      "evidence_gaps",
    ],
    materialTitle: "Operations handoff material",
    materialFields: [
      { key: "operations_summary", label: "Operations summary" },
      { key: "sections", label: "Handoff sections" },
      { key: "execution_prerequisites", label: "Execution prerequisites" },
      { key: "blocking_conditions", label: "Blocking conditions" },
      { key: "support_references", label: "Supporting references" },
      { key: "evidence_gaps", label: "Evidence gaps" },
      { key: "review_required", label: "Review required" },
      { key: "state", label: "Review posture" },
      { key: "scope", label: "Permitted scope" },
    ],
  },
  "exception-summary": {
    scopeLabel: "Mandate exception review summary",
    packId: "dpm_exception_summary.pack",
    workflowSurface: "dpm-exception-summary-ai-evidence",
    sourceSupportabilityAuthority: "lotus-manage:RFC-0038",
    liveSourceSupportabilityStates: ["READY"],
    sourceInputField: "exception_summary_input",
    sourceIdentityField: "exception_id",
    requestedOutputs: [
      "exception_summary",
      "severity_summary",
      "recommended_triage",
      "support_references",
      "evidence_gaps",
    ],
    materialTitle: "Exception review material",
    materialFields: [
      { key: "exception_summary", label: "Exception summary" },
      { key: "severity_summary", label: "Severity assessment" },
      { key: "recommended_triage", label: "Recommended triage" },
      { key: "support_references", label: "Supporting references" },
      { key: "evidence_gaps", label: "Evidence gaps" },
      { key: "exception_count", label: "Exceptions covered" },
      { key: "exception_summary_status", label: "Review posture" },
      { key: "state", label: "Review posture" },
      { key: "scope", label: "Permitted scope" },
    ],
  },
  "outcome-narrative": {
    scopeLabel: "Outcome review narrative",
    packId: "outcome_review_narrative.pack",
    workflowSurface: "dpm-outcome-review-ai-evidence",
    sourceSupportabilityAuthority: "lotus-manage:RFC-0042",
    liveSourceSupportabilityStates: ["SUPPORTED", "READY"],
    sourceInputField: "ai_evidence_input",
    sourceIdentityField: "outcome_review_id",
    requestedOutputs: [
      "pm_summary",
      "cio_summary",
      "control_summary",
      "evidence_gaps",
    ],
    materialTitle: "Outcome review material",
    materialFields: [
      { key: "pm_summary", label: "Portfolio manager summary" },
      { key: "cio_summary", label: "Chief investment office summary" },
      { key: "control_summary", label: "Investment control summary" },
      { key: "narrative", label: "Outcome narrative" },
      { key: "evidence_gaps", label: "Evidence gaps" },
      { key: "outcome_review_narrative_status", label: "Review posture" },
      { key: "state", label: "Review posture" },
      { key: "scope", label: "Permitted scope" },
    ],
  },
  "pm-quality-summary": {
    scopeLabel: "Portfolio-manager quality support summary",
    packId: "pm_quality_summary.pack",
    workflowSurface: "dpm-pm-quality-ai-evidence",
    sourceSupportabilityAuthority: "lotus-manage:RFC-0042/PM_OPERATING_QUALITY",
    liveSourceSupportabilityStates: ["READY"],
    sourceInputField: "score_run",
    sourceIdentityField: "score_run_id",
    requestedOutputs: [
      "score_run_summary",
      "governance_summary",
      "fairness_review_posture",
      "support_references",
      "evidence_gaps",
    ],
    materialTitle: "Portfolio-manager quality material",
    materialFields: [
      { key: "score_run_summary", label: "Quality summary" },
      { key: "summary", label: "Quality summary" },
      { key: "governance_summary", label: "Governance assessment" },
      { key: "fairness_review_posture", label: "Fairness review posture" },
      { key: "support_references", label: "Supporting references" },
      { key: "evidence_gaps", label: "Evidence gaps" },
      { key: "summary_status", label: "Review posture" },
      { key: "state", label: "Review posture" },
      { key: "scope", label: "Permitted scope" },
    ],
  },
} as const;

export type DpmAiWorkflowFamily = keyof typeof DPM_AI_WORKFLOW_PROFILES;
export type DpmAiWorkflowProfile =
  (typeof DPM_AI_WORKFLOW_PROFILES)[DpmAiWorkflowFamily];

export function getDpmAiWorkflowProfile(family: DpmAiWorkflowFamily) {
  return DPM_AI_WORKFLOW_PROFILES[family];
}
