export const MANAGE_WORKFLOW_LABELS = {
  portfolioManagementDecisions: "Portfolio management decisions",
  mandateReview: "Mandate review",
  mandateHealth: "Mandate health",
  attentionItems: "Attention items",
  openAttentionItems: "Open attention items",
  sourceExceptions: "Source exceptions",
  needsAttention: "Needs attention",
  dataAvailability: "Data availability",
  mandateHealthDimensions: "Mandate health dimensions",
  asOfDate: "As-of date",
} as const;

export const MANAGE_HEALTH_DIMENSION_LABELS = {
  dataAvailability: MANAGE_WORKFLOW_LABELS.dataAvailability,
  allocationDrift: "Allocation drift",
  riskDrift: "Risk drift",
  cashLiquidity: "Cash liquidity",
  taxAndTurnover: "Tax and turnover",
  eligibilityRestrictions: "Eligibility restrictions",
  performanceReview: "Performance review",
  reviewReadiness: "Review readiness",
  reviewCadence: "Review cadence",
  modelFreshness: "Model freshness",
  mandateConstraints: "Mandate constraints",
} as const;

export const MANAGE_REBALANCE_LABELS = {
  campaignLaunchDecision: "Campaign launch decision",
  campaignLaunchHistory: "Campaign launch history",
  campaignLifecycleEvidence: "Campaign lifecycle evidence",
  previewReadiness: "Preview readiness",
  launchReadiness: "Launch readiness",
  asOfDate: "As-of date",
  previewAsOfDate: "Preview as-of date",
  reviewedBy: "Reviewed by",
  previewReviewedBy: "Preview reviewed by",
  rebalanceWave: "Rebalance wave",
  rebalanceWaveReference: "Rebalance wave reference",
  supportReference: "Support reference",
  replayKey: "Replay key",
} as const;

export const MANAGE_OUTCOME_REVIEW_LABELS = {
  screenTitle: "Outcome reviews",
  panelTitle: "Outcome comparison",
  screenDescription:
    "Compare expected and realised outcomes, review mandate impact, and confirm evidence readiness.",
  reviewPosture: "Review status",
  comparisonOutcome: "Comparison outcome",
  driftImprovement: "Drift improvement",
  evidencePack: "Evidence pack",
  recommendedActions: "Recommended actions",
  selectedReviewDetail: "Selected review detail",
  reviewTimeline: "Review timeline",
  reviewWindow: "Review window",
  reportPreparation: "Report preparation",
  aiAssistedReviewSummary: "AI-assisted review summary",
  sourceEvidence: "Source evidence",
  clientCommunicationControls: "Client communication controls",
  mandateImpact: "Mandate impact",
  internalOutcomeRationale: "Internal outcome rationale",
  evidenceAvailability: "Evidence availability",
  evidenceSources: "Evidence sources",
  recordedEvidenceProfile: "Recorded evidence profile",
  sourceRecorded: "Source recorded",
  expectedOutcome: "Expected outcome",
  realisedOutcome: "Realised outcome",
  prepareAiAssistedReviewSummary: "Prepare AI-assisted review summary",
  preparingAiAssistedReviewSummary: "Preparing AI-assisted review summary",
  withinExpectedTolerance: "Within expected tolerance",
  reviewPending: "Review pending",
  outsideExpectedTolerance: "Outside expected tolerance",
  blocked: "Blocked",
  reviewRequired: "Review required",
  outcomeEvidenceReady: "Outcome evidence ready",
  needsAttention: MANAGE_WORKFLOW_LABELS.needsAttention,
  readyForAdviserReview: "Ready for adviser review",
  adviserReviewPending: "Adviser review pending",
  escalationRequired: "Escalation required",
} as const;
